name: checkout repo

on: [push]


jobs:

    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: list all files before
              run: ls -a


            - name: checkout after
              uses: actions/checkout@v4
              run: ls -a

              




    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: list our files before
              run: ls -a

            - name: checkout
              run: |

                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files after
              run: ls -a
