name: Repository events

on: 
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    issues:


jobs:
  checkout-tests:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $GITHUB_SHA
        echo $GITHUB_REF
    - uses: actions/checkout@v4
